### ISSUE TITLE
PHP error AdminUi.php

### ISSUE THREAD

**Issue by vslonska** [jakub-klapka/wp-secure-post-with-link#1]
Hello,

Thanks for the plugin. I have a php error when activating the plugin, once on admin pages, and for each query on front end pages.

Notice: Trying to get property of non-object in /wp-content/plugins/secure-post-with-link/Controllers/AdminUi.php on line 130

Regards,

**Comment by vslonska** [comment]
In my case, it's because $wp_post is an integer (post id), I don't know why.
But it can be solved putting `$wp_post = get_post($wp_post);` at the beginning of `public function modifyPermalinkOnSecuredPosts( $link, $wp_post )` line 128 of Controllers/AdminUi.php.

With that, it will work if $wp_post is an integer or if it's an object.

**Comment by jakub-klapka** [comment]
Hello,
thanks a lot for report and investigation.
I see the problem now. WP filter `page_link` works differently, than `post_link`. `post_link` passes WP_Post object and `page_link` passes post_id. What a consistency :)
Never noticed that, since I usually use custom post types or posts. I'll try to release fix during weekend.

Thanks, Jakub

**Comment by jakub-klapka** [comment]
Resolved in v1.2.2

Thanks for help

**Comment by vslonska** [comment]
Hello,

Thanks for your quick answer and solution.

I confirm that it works well.

Thanks a lot,
